version: '2'

networks:
  fabric-ca:
    name: networkUK

services:
  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=tls-ca
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/tls-ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7052:7052

  rca-airline:
    container_name: rca-airline
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b rca-airline-admin:rca-airline-adminpw --port 7054'
    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=rca-airline
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/airline/ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7054:7054

  rca-ansp:
    container_name: rca-ansp
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b rca-ansp-admin:rca-ansp-adminpw --port 7055'

    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=rca-ansp
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/ansp/ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7055:7055

  rca-airport:
    container_name: rca-airport
    image: hyperledger/fabric-ca:latest
    command: sh -c 'fabric-ca-server start -d -b rca-airport-admin:rca-airport-adminpw --port 7056'

    environment:
        - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=rca-airport
        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
        - FABRIC_CA_SERVER_DEBUG=true
    volumes:
        - /tmp/hyperledger/airport/ca:/tmp/hyperledger/fabric-ca
    networks:
        - fabric-ca
    ports:
        - 7056:7056

  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"
    networks:
      - fabric-ca

  peer1-airline:
    container_name: peer1-airline
    image: hyperledger/fabric-peer:latest
    environment:
        - CORE_PEER_ID=peer1-airline
        - CORE_PEER_ADDRESS=peer1-airline:7051
        - CORE_PEER_LOCALMSPID=airlineMSP
        - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/airline/peer1/msp
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkUK
        - FABRIC_LOGGING_SPEC=info
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/airline/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/airline/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/airline/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-airline:7051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
        - couchdb0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/airline/peer1
    volumes:
        - /var/run:/host/var/run
        - /tmp/hyperledger/airline/peer1:/tmp/hyperledger/airline/peer1
    ports:
        - 7051:7051
    networks:
        - fabric-ca

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      - fabric-ca
        
  peer1-ansp:
    container_name: peer1-ansp
    image: hyperledger/fabric-peer:latest
    environment:
        - CORE_PEER_ID=peer1-ansp
        - CORE_PEER_ADDRESS=peer1-ansp:8051
        - CORE_PEER_LOCALMSPID=anspMSP
        - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/ansp/peer1/msp
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkUK
        - FABRIC_LOGGING_SPEC=info
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/ansp/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/ansp/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/ansp/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-ansp:8051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
        - couchdb1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/ansp/peer1
    volumes:
        - /var/run:/host/var/run
        - /tmp/hyperledger/ansp/peer1:/tmp/hyperledger/ansp/peer1
    ports:
        - 8051:8051
    networks:
        - fabric-ca

  couchdb2:
    container_name: couchdb2
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "9984:5984"
    networks:
      - fabric-ca

  peer1-airport:
    container_name: peer1-airport
    image: hyperledger/fabric-peer:latest
    environment:
        - CORE_PEER_ID=peer1-airport
        - CORE_PEER_ADDRESS=peer1-airport:9051
        - CORE_PEER_LOCALMSPID=airportMSP
        - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/airport/peer1/msp
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=networkUK
        - FABRIC_LOGGING_SPEC=info
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/airport/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/airport/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/airport/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-airport:9051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
        - couchdb2
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/airport/peer1
    volumes:
        - /var/run:/host/var/run
        - /tmp/hyperledger/airport/peer1:/tmp/hyperledger/airport/peer1
    ports:
        - 9051:9051
    networks:
        - fabric-ca 

  orderer1-airline:
    container_name: orderer1-airline
    image: hyperledger/fabric-orderer:2.3.2
    environment:
        - ORDERER_HOME=/tmp/hyperledger/orderer
        - ORDERER_HOST=orderer1-airline
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        # - ORDERER_GENERAL_GENESISMETHOD=file
        # - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/airline/orderer1/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=airlineMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/airline/orderer1/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/airline/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/airline/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/airline/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/airline/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/airline/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/airline/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
        - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7080
        - ORDERER_ADMIN_TLS_ENABLED=true
        - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/airline/orderer1/tls-msp/keystore/key.pem
        - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/airline/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
        - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/airline/admin/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    volumes:
        - /tmp/hyperledger/airline/orderer1:/tmp/hyperledger/airline/orderer1/
        - /tmp/hyperledger/airline/admin:/tmp/hyperledger/airline/admin/
    ports:
        - 7050:7050
        - 7080:7080
    networks:
        - fabric-ca

  orderer1-ansp:
    container_name: orderer1-ansp
    image: hyperledger/fabric-orderer:2.3.2
    environment:
        - ORDERER_HOME=/tmp/hyperledger/orderer
        - ORDERER_HOST=orderer1-ansp
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        # - ORDERER_GENERAL_GENESISMETHOD=file
        # - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/ansp/orderer1/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=anspMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/ansp/orderer1/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/ansp/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/ansp/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/ansp/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/ansp/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/ansp/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/ansp/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
        - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7080
        - ORDERER_ADMIN_TLS_ENABLED=true
        - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/ansp/orderer1/tls-msp/keystore/key.pem
        - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/ansp/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
        - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/ansp/admin/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_CHANNELPARTICIPATION_ENABLED=true        
    volumes:
        - /tmp/hyperledger/ansp/orderer1:/tmp/hyperledger/ansp/orderer1/
        - /tmp/hyperledger/ansp/admin:/tmp/hyperledger/ansp/admin/
    ports:
        - 8050:7050
        - 8080:7080
    networks:
        - fabric-ca

  orderer1-airport:
    container_name: orderer1-airport
    image: hyperledger/fabric-orderer:2.3.2
    environment:
        - ORDERER_HOME=/tmp/hyperledger/orderer
        - ORDERER_HOST=orderer1-airport
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        # - ORDERER_GENERAL_GENESISMETHOD=file
        # - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/airport/orderer1/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=airportMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/airport/orderer1/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/airport/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/airport/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/airport/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/airport/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/airport/orderer1/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/airport/orderer1/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
        - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7080
        - ORDERER_ADMIN_TLS_ENABLED=true
        - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/airport/orderer1/tls-msp/keystore/key.pem
        - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/airport/orderer1/tls-msp/signcerts/cert.pem
        - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
        - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/airport/admin/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
        - ORDERER_CHANNELPARTICIPATION_ENABLED=true        
    volumes:
        - /tmp/hyperledger/airport/orderer1:/tmp/hyperledger/airport/orderer1/
        - /tmp/hyperledger/airport/admin:/tmp/hyperledger/airport/admin/
    ports:
        - 9050:7050
        - 9080:7080
    networks:
        - fabric-ca